### ISSUE TITLE
advantages?

### ISSUE THREAD

**Issue by ghost** [Shopify/autoload_reloader#1]
it would be nice if there were a section in the README explaining the advantages of using this library

**Comment by prog1dev** [comment]
Isnt it this part https://github.com/Shopify/autoload_reloader#why-is-using-moduleautoload-awesome-compared-to-const_missing?

**Comment by dylanahsmith** [comment]
The README does have the advantages, but they are pretty far down after the initial description.  Perhaps that description could summarize the advantages and use an anchor link to the "Why is using Module#autoload awesome compared to const_missing" section.

**Comment by olivierlacan** [comment]
I agree with this suggestion. This got me really excited but it's not until a bit too low into the README that I finally understood the benefits.

**Comment by ghost** [comment]
^ exactly, it would be nice if that section were moved up and maybe a note on any performance improvement (or whether performance remains the same).
