### ISSUE TITLE
"No description, website, or topics provided."

### ISSUE THREAD

**Issue by grosser** [Shopify/autoload_reloader#5]
plz fill them out :)

**Comment by rafaelfranca** [comment]
This is an experimental project. There is no need for description, website or topics just yet.

**Comment by rafaelfranca** [comment]
But I added the experimental nature of it on it anyway 😄

**Comment by grosser** [comment]
hope this gets ready soon, sounds so good :D
.... better be in rails 6, no pressure ;)

**Comment by rafaelfranca** [comment]
Yeah, it is the plan to integrate to Rails, but I don't promise it will be in 6.0.
