### ISSUE TITLE
Seems like autoload is (still) on the chopping block for Ruby 3

### ISSUE THREAD

**Issue by olivierlacan** [Shopify/autoload_reloader#7]
Might be worth taking into consideration for the medium/long term: https://bugs.ruby-lang.org/issues/5653#note-34

**Comment by rafaelfranca** [comment]
This project is "dead". See https://medium.com/@fxn/zeitwerk-a-new-code-loader-for-ruby-ae7895977e73.

Although we still need to comment in that thread to say that Zeitwerk is also using autoload.
